// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: cursor-tab-server-agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*AgentClientMessage_RunRequest
	//	*AgentClientMessage_PrewarmRequest
	Message       isAgentClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentClientMessage) Reset() {
	*x = AgentClientMessage{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentClientMessage) ProtoMessage() {}

func (x *AgentClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentClientMessage.ProtoReflect.Descriptor instead.
func (*AgentClientMessage) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentClientMessage) GetMessage() isAgentClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AgentClientMessage) GetRunRequest() *AgentRunRequest {
	if x != nil {
		if x, ok := x.Message.(*AgentClientMessage_RunRequest); ok {
			return x.RunRequest
		}
	}
	return nil
}

func (x *AgentClientMessage) GetPrewarmRequest() *PrewarmRequest {
	if x != nil {
		if x, ok := x.Message.(*AgentClientMessage_PrewarmRequest); ok {
			return x.PrewarmRequest
		}
	}
	return nil
}

type isAgentClientMessage_Message interface {
	isAgentClientMessage_Message()
}

type AgentClientMessage_RunRequest struct {
	RunRequest *AgentRunRequest `protobuf:"bytes,1,opt,name=run_request,json=runRequest,proto3,oneof"`
}

type AgentClientMessage_PrewarmRequest struct {
	PrewarmRequest *PrewarmRequest `protobuf:"bytes,8,opt,name=prewarm_request,json=prewarmRequest,proto3,oneof"`
}

func (*AgentClientMessage_RunRequest) isAgentClientMessage_Message() {}

func (*AgentClientMessage_PrewarmRequest) isAgentClientMessage_Message() {}

type AgentRunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelDetails   *ModelDetails          `protobuf:"bytes,3,opt,name=model_details,json=modelDetails,proto3" json:"model_details,omitempty"`
	RequestedModel *RequestedModel        `protobuf:"bytes,9,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentRunRequest) Reset() {
	*x = AgentRunRequest{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRunRequest) ProtoMessage() {}

func (x *AgentRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRunRequest.ProtoReflect.Descriptor instead.
func (*AgentRunRequest) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentRunRequest) GetModelDetails() *ModelDetails {
	if x != nil {
		return x.ModelDetails
	}
	return nil
}

func (x *AgentRunRequest) GetRequestedModel() *RequestedModel {
	if x != nil {
		return x.RequestedModel
	}
	return nil
}

type PrewarmRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ModelDetails   *ModelDetails          `protobuf:"bytes,1,opt,name=model_details,json=modelDetails,proto3" json:"model_details,omitempty"`
	RequestedModel *RequestedModel        `protobuf:"bytes,9,opt,name=requested_model,json=requestedModel,proto3" json:"requested_model,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PrewarmRequest) Reset() {
	*x = PrewarmRequest{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrewarmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrewarmRequest) ProtoMessage() {}

func (x *PrewarmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrewarmRequest.ProtoReflect.Descriptor instead.
func (*PrewarmRequest) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PrewarmRequest) GetModelDetails() *ModelDetails {
	if x != nil {
		return x.ModelDetails
	}
	return nil
}

func (x *PrewarmRequest) GetRequestedModel() *RequestedModel {
	if x != nil {
		return x.RequestedModel
	}
	return nil
}

type AgentServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentServerMessage) Reset() {
	*x = AgentServerMessage{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentServerMessage) ProtoMessage() {}

func (x *AgentServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentServerMessage.ProtoReflect.Descriptor instead.
func (*AgentServerMessage) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{3}
}

type ApiKeyCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       *string                `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3,oneof" json:"base_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiKeyCredentials) Reset() {
	*x = ApiKeyCredentials{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiKeyCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiKeyCredentials) ProtoMessage() {}

func (x *ApiKeyCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiKeyCredentials.ProtoReflect.Descriptor instead.
func (*ApiKeyCredentials) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ApiKeyCredentials) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *ApiKeyCredentials) GetBaseUrl() string {
	if x != nil && x.BaseUrl != nil {
		return *x.BaseUrl
	}
	return ""
}

type AzureCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	BaseUrl       string                 `protobuf:"bytes,2,opt,name=base_url,json=baseUrl,proto3" json:"base_url,omitempty"`
	Deployment    string                 `protobuf:"bytes,3,opt,name=deployment,proto3" json:"deployment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AzureCredentials) Reset() {
	*x = AzureCredentials{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzureCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzureCredentials) ProtoMessage() {}

func (x *AzureCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzureCredentials.ProtoReflect.Descriptor instead.
func (*AzureCredentials) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AzureCredentials) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *AzureCredentials) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *AzureCredentials) GetDeployment() string {
	if x != nil {
		return x.Deployment
	}
	return ""
}

type BedrockCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BedrockCredentials) Reset() {
	*x = BedrockCredentials{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BedrockCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BedrockCredentials) ProtoMessage() {}

func (x *BedrockCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BedrockCredentials.ProtoReflect.Descriptor instead.
func (*BedrockCredentials) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{6}
}

type ThinkingDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingDetails) Reset() {
	*x = ThinkingDetails{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingDetails) ProtoMessage() {}

func (x *ThinkingDetails) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingDetails.ProtoReflect.Descriptor instead.
func (*ThinkingDetails) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{7}
}

type ModelDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ModelId          string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ThinkingDetails  *ThinkingDetails       `protobuf:"bytes,2,opt,name=thinking_details,json=thinkingDetails,proto3" json:"thinking_details,omitempty"`
	DisplayModelId   string                 `protobuf:"bytes,3,opt,name=display_model_id,json=displayModelId,proto3" json:"display_model_id,omitempty"`
	DisplayName      string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	DisplayNameShort string                 `protobuf:"bytes,5,opt,name=display_name_short,json=displayNameShort,proto3" json:"display_name_short,omitempty"`
	Aliases          []string               `protobuf:"bytes,6,rep,name=aliases,proto3" json:"aliases,omitempty"`
	MaxMode          *bool                  `protobuf:"varint,7,opt,name=max_mode,json=maxMode,proto3,oneof" json:"max_mode,omitempty"`
	// Types that are valid to be assigned to Credentials:
	//
	//	*ModelDetails_ApiKeyCredentials
	//	*ModelDetails_AzureCredentials
	//	*ModelDetails_BedrockCredentials
	Credentials   isModelDetails_Credentials `protobuf_oneof:"credentials"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelDetails) Reset() {
	*x = ModelDetails{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDetails) ProtoMessage() {}

func (x *ModelDetails) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDetails.ProtoReflect.Descriptor instead.
func (*ModelDetails) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ModelDetails) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelDetails) GetThinkingDetails() *ThinkingDetails {
	if x != nil {
		return x.ThinkingDetails
	}
	return nil
}

func (x *ModelDetails) GetDisplayModelId() string {
	if x != nil {
		return x.DisplayModelId
	}
	return ""
}

func (x *ModelDetails) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ModelDetails) GetDisplayNameShort() string {
	if x != nil {
		return x.DisplayNameShort
	}
	return ""
}

func (x *ModelDetails) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ModelDetails) GetMaxMode() bool {
	if x != nil && x.MaxMode != nil {
		return *x.MaxMode
	}
	return false
}

func (x *ModelDetails) GetCredentials() isModelDetails_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ModelDetails) GetApiKeyCredentials() *ApiKeyCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*ModelDetails_ApiKeyCredentials); ok {
			return x.ApiKeyCredentials
		}
	}
	return nil
}

func (x *ModelDetails) GetAzureCredentials() *AzureCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*ModelDetails_AzureCredentials); ok {
			return x.AzureCredentials
		}
	}
	return nil
}

func (x *ModelDetails) GetBedrockCredentials() *BedrockCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*ModelDetails_BedrockCredentials); ok {
			return x.BedrockCredentials
		}
	}
	return nil
}

type isModelDetails_Credentials interface {
	isModelDetails_Credentials()
}

type ModelDetails_ApiKeyCredentials struct {
	ApiKeyCredentials *ApiKeyCredentials `protobuf:"bytes,8,opt,name=api_key_credentials,json=apiKeyCredentials,proto3,oneof"`
}

type ModelDetails_AzureCredentials struct {
	AzureCredentials *AzureCredentials `protobuf:"bytes,9,opt,name=azure_credentials,json=azureCredentials,proto3,oneof"`
}

type ModelDetails_BedrockCredentials struct {
	BedrockCredentials *BedrockCredentials `protobuf:"bytes,10,opt,name=bedrock_credentials,json=bedrockCredentials,proto3,oneof"`
}

func (*ModelDetails_ApiKeyCredentials) isModelDetails_Credentials() {}

func (*ModelDetails_AzureCredentials) isModelDetails_Credentials() {}

func (*ModelDetails_BedrockCredentials) isModelDetails_Credentials() {}

type RequestedModel struct {
	state      protoimpl.MessageState                `protogen:"open.v1"`
	ModelId    string                                `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	MaxMode    bool                                  `protobuf:"varint,2,opt,name=max_mode,json=maxMode,proto3" json:"max_mode,omitempty"`
	Parameters []*RequestedModel_ModelParameterValue `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Types that are valid to be assigned to Credentials:
	//
	//	*RequestedModel_ApiKeyCredentials
	//	*RequestedModel_AzureCredentials
	//	*RequestedModel_BedrockCredentials
	Credentials   isRequestedModel_Credentials `protobuf_oneof:"credentials"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestedModel) Reset() {
	*x = RequestedModel{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedModel) ProtoMessage() {}

func (x *RequestedModel) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedModel.ProtoReflect.Descriptor instead.
func (*RequestedModel) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RequestedModel) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *RequestedModel) GetMaxMode() bool {
	if x != nil {
		return x.MaxMode
	}
	return false
}

func (x *RequestedModel) GetParameters() []*RequestedModel_ModelParameterValue {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *RequestedModel) GetCredentials() isRequestedModel_Credentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *RequestedModel) GetApiKeyCredentials() *ApiKeyCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*RequestedModel_ApiKeyCredentials); ok {
			return x.ApiKeyCredentials
		}
	}
	return nil
}

func (x *RequestedModel) GetAzureCredentials() *AzureCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*RequestedModel_AzureCredentials); ok {
			return x.AzureCredentials
		}
	}
	return nil
}

func (x *RequestedModel) GetBedrockCredentials() *BedrockCredentials {
	if x != nil {
		if x, ok := x.Credentials.(*RequestedModel_BedrockCredentials); ok {
			return x.BedrockCredentials
		}
	}
	return nil
}

type isRequestedModel_Credentials interface {
	isRequestedModel_Credentials()
}

type RequestedModel_ApiKeyCredentials struct {
	ApiKeyCredentials *ApiKeyCredentials `protobuf:"bytes,4,opt,name=api_key_credentials,json=apiKeyCredentials,proto3,oneof"`
}

type RequestedModel_AzureCredentials struct {
	AzureCredentials *AzureCredentials `protobuf:"bytes,5,opt,name=azure_credentials,json=azureCredentials,proto3,oneof"`
}

type RequestedModel_BedrockCredentials struct {
	BedrockCredentials *BedrockCredentials `protobuf:"bytes,6,opt,name=bedrock_credentials,json=bedrockCredentials,proto3,oneof"`
}

func (*RequestedModel_ApiKeyCredentials) isRequestedModel_Credentials() {}

func (*RequestedModel_AzureCredentials) isRequestedModel_Credentials() {}

func (*RequestedModel_BedrockCredentials) isRequestedModel_Credentials() {}

type RequestedModel_ModelParameterValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestedModel_ModelParameterValue) Reset() {
	*x = RequestedModel_ModelParameterValue{}
	mi := &file_cursor_tab_server_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedModel_ModelParameterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedModel_ModelParameterValue) ProtoMessage() {}

func (x *RequestedModel_ModelParameterValue) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedModel_ModelParameterValue.ProtoReflect.Descriptor instead.
func (*RequestedModel_ModelParameterValue) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_agent_proto_rawDescGZIP(), []int{9, 0}
}

func (x *RequestedModel_ModelParameterValue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestedModel_ModelParameterValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_cursor_tab_server_agent_proto protoreflect.FileDescriptor

const file_cursor_tab_server_agent_proto_rawDesc = "" +
	"\n" +
	"\x1dcursor-tab-server-agent.proto\x12\bagent.v1\"\xa2\x01\n" +
	"\x12AgentClientMessage\x12<\n" +
	"\vrun_request\x18\x01 \x01(\v2\x19.agent.v1.AgentRunRequestH\x00R\n" +
	"runRequest\x12C\n" +
	"\x0fprewarm_request\x18\b \x01(\v2\x18.agent.v1.PrewarmRequestH\x00R\x0eprewarmRequestB\t\n" +
	"\amessage\"\x91\x01\n" +
	"\x0fAgentRunRequest\x12;\n" +
	"\rmodel_details\x18\x03 \x01(\v2\x16.agent.v1.ModelDetailsR\fmodelDetails\x12A\n" +
	"\x0frequested_model\x18\t \x01(\v2\x18.agent.v1.RequestedModelR\x0erequestedModel\"\x90\x01\n" +
	"\x0ePrewarmRequest\x12;\n" +
	"\rmodel_details\x18\x01 \x01(\v2\x16.agent.v1.ModelDetailsR\fmodelDetails\x12A\n" +
	"\x0frequested_model\x18\t \x01(\v2\x18.agent.v1.RequestedModelR\x0erequestedModel\"\x14\n" +
	"\x12AgentServerMessage\"Y\n" +
	"\x11ApiKeyCredentials\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1e\n" +
	"\bbase_url\x18\x02 \x01(\tH\x00R\abaseUrl\x88\x01\x01B\v\n" +
	"\t_base_url\"f\n" +
	"\x10AzureCredentials\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bbase_url\x18\x02 \x01(\tR\abaseUrl\x12\x1e\n" +
	"\n" +
	"deployment\x18\x03 \x01(\tR\n" +
	"deployment\"\x14\n" +
	"\x12BedrockCredentials\"\x11\n" +
	"\x0fThinkingDetails\"\xab\x04\n" +
	"\fModelDetails\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12D\n" +
	"\x10thinking_details\x18\x02 \x01(\v2\x19.agent.v1.ThinkingDetailsR\x0fthinkingDetails\x12(\n" +
	"\x10display_model_id\x18\x03 \x01(\tR\x0edisplayModelId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12,\n" +
	"\x12display_name_short\x18\x05 \x01(\tR\x10displayNameShort\x12\x18\n" +
	"\aaliases\x18\x06 \x03(\tR\aaliases\x12\x1e\n" +
	"\bmax_mode\x18\a \x01(\bH\x01R\amaxMode\x88\x01\x01\x12M\n" +
	"\x13api_key_credentials\x18\b \x01(\v2\x1b.agent.v1.ApiKeyCredentialsH\x00R\x11apiKeyCredentials\x12I\n" +
	"\x11azure_credentials\x18\t \x01(\v2\x1a.agent.v1.AzureCredentialsH\x00R\x10azureCredentials\x12O\n" +
	"\x13bedrock_credentials\x18\n" +
	" \x01(\v2\x1c.agent.v1.BedrockCredentialsH\x00R\x12bedrockCredentialsB\r\n" +
	"\vcredentialsB\v\n" +
	"\t_max_mode\"\xcb\x03\n" +
	"\x0eRequestedModel\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x19\n" +
	"\bmax_mode\x18\x02 \x01(\bR\amaxMode\x12L\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2,.agent.v1.RequestedModel.ModelParameterValueR\n" +
	"parameters\x12M\n" +
	"\x13api_key_credentials\x18\x04 \x01(\v2\x1b.agent.v1.ApiKeyCredentialsH\x00R\x11apiKeyCredentials\x12I\n" +
	"\x11azure_credentials\x18\x05 \x01(\v2\x1a.agent.v1.AzureCredentialsH\x00R\x10azureCredentials\x12O\n" +
	"\x13bedrock_credentials\x18\x06 \x01(\v2\x1c.agent.v1.BedrockCredentialsH\x00R\x12bedrockCredentials\x1a;\n" +
	"\x13ModelParameterValue\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB\r\n" +
	"\vcredentialsBDZBgithub.com/leokun/cursor-tab-server/internal/proto/agentv1;agentv1b\x06proto3"

var (
	file_cursor_tab_server_agent_proto_rawDescOnce sync.Once
	file_cursor_tab_server_agent_proto_rawDescData []byte
)

func file_cursor_tab_server_agent_proto_rawDescGZIP() []byte {
	file_cursor_tab_server_agent_proto_rawDescOnce.Do(func() {
		file_cursor_tab_server_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cursor_tab_server_agent_proto_rawDesc), len(file_cursor_tab_server_agent_proto_rawDesc)))
	})
	return file_cursor_tab_server_agent_proto_rawDescData
}

var file_cursor_tab_server_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cursor_tab_server_agent_proto_goTypes = []any{
	(*AgentClientMessage)(nil),                 // 0: agent.v1.AgentClientMessage
	(*AgentRunRequest)(nil),                    // 1: agent.v1.AgentRunRequest
	(*PrewarmRequest)(nil),                     // 2: agent.v1.PrewarmRequest
	(*AgentServerMessage)(nil),                 // 3: agent.v1.AgentServerMessage
	(*ApiKeyCredentials)(nil),                  // 4: agent.v1.ApiKeyCredentials
	(*AzureCredentials)(nil),                   // 5: agent.v1.AzureCredentials
	(*BedrockCredentials)(nil),                 // 6: agent.v1.BedrockCredentials
	(*ThinkingDetails)(nil),                    // 7: agent.v1.ThinkingDetails
	(*ModelDetails)(nil),                       // 8: agent.v1.ModelDetails
	(*RequestedModel)(nil),                     // 9: agent.v1.RequestedModel
	(*RequestedModel_ModelParameterValue)(nil), // 10: agent.v1.RequestedModel.ModelParameterValue
}
var file_cursor_tab_server_agent_proto_depIdxs = []int32{
	1,  // 0: agent.v1.AgentClientMessage.run_request:type_name -> agent.v1.AgentRunRequest
	2,  // 1: agent.v1.AgentClientMessage.prewarm_request:type_name -> agent.v1.PrewarmRequest
	8,  // 2: agent.v1.AgentRunRequest.model_details:type_name -> agent.v1.ModelDetails
	9,  // 3: agent.v1.AgentRunRequest.requested_model:type_name -> agent.v1.RequestedModel
	8,  // 4: agent.v1.PrewarmRequest.model_details:type_name -> agent.v1.ModelDetails
	9,  // 5: agent.v1.PrewarmRequest.requested_model:type_name -> agent.v1.RequestedModel
	7,  // 6: agent.v1.ModelDetails.thinking_details:type_name -> agent.v1.ThinkingDetails
	4,  // 7: agent.v1.ModelDetails.api_key_credentials:type_name -> agent.v1.ApiKeyCredentials
	5,  // 8: agent.v1.ModelDetails.azure_credentials:type_name -> agent.v1.AzureCredentials
	6,  // 9: agent.v1.ModelDetails.bedrock_credentials:type_name -> agent.v1.BedrockCredentials
	10, // 10: agent.v1.RequestedModel.parameters:type_name -> agent.v1.RequestedModel.ModelParameterValue
	4,  // 11: agent.v1.RequestedModel.api_key_credentials:type_name -> agent.v1.ApiKeyCredentials
	5,  // 12: agent.v1.RequestedModel.azure_credentials:type_name -> agent.v1.AzureCredentials
	6,  // 13: agent.v1.RequestedModel.bedrock_credentials:type_name -> agent.v1.BedrockCredentials
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cursor_tab_server_agent_proto_init() }
func file_cursor_tab_server_agent_proto_init() {
	if File_cursor_tab_server_agent_proto != nil {
		return
	}
	file_cursor_tab_server_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentClientMessage_RunRequest)(nil),
		(*AgentClientMessage_PrewarmRequest)(nil),
	}
	file_cursor_tab_server_agent_proto_msgTypes[4].OneofWrappers = []any{}
	file_cursor_tab_server_agent_proto_msgTypes[8].OneofWrappers = []any{
		(*ModelDetails_ApiKeyCredentials)(nil),
		(*ModelDetails_AzureCredentials)(nil),
		(*ModelDetails_BedrockCredentials)(nil),
	}
	file_cursor_tab_server_agent_proto_msgTypes[9].OneofWrappers = []any{
		(*RequestedModel_ApiKeyCredentials)(nil),
		(*RequestedModel_AzureCredentials)(nil),
		(*RequestedModel_BedrockCredentials)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cursor_tab_server_agent_proto_rawDesc), len(file_cursor_tab_server_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_tab_server_agent_proto_goTypes,
		DependencyIndexes: file_cursor_tab_server_agent_proto_depIdxs,
		MessageInfos:      file_cursor_tab_server_agent_proto_msgTypes,
	}.Build()
	File_cursor_tab_server_agent_proto = out.File
	file_cursor_tab_server_agent_proto_goTypes = nil
	file_cursor_tab_server_agent_proto_depIdxs = nil
}
