// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.34.0
// source: cursor-tab-server-aiserver.proto

package aiserverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidiAppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	RequestId     *BidiRequestId         `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AppendSeqno   int64                  `protobuf:"varint,3,opt,name=append_seqno,json=appendSeqno,proto3" json:"append_seqno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiAppendRequest) Reset() {
	*x = BidiAppendRequest{}
	mi := &file_cursor_tab_server_aiserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiAppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiAppendRequest) ProtoMessage() {}

func (x *BidiAppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_aiserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiAppendRequest.ProtoReflect.Descriptor instead.
func (*BidiAppendRequest) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_aiserver_proto_rawDescGZIP(), []int{0}
}

func (x *BidiAppendRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *BidiAppendRequest) GetRequestId() *BidiRequestId {
	if x != nil {
		return x.RequestId
	}
	return nil
}

func (x *BidiAppendRequest) GetAppendSeqno() int64 {
	if x != nil {
		return x.AppendSeqno
	}
	return 0
}

type BidiRequestId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidiRequestId) Reset() {
	*x = BidiRequestId{}
	mi := &file_cursor_tab_server_aiserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidiRequestId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidiRequestId) ProtoMessage() {}

func (x *BidiRequestId) ProtoReflect() protoreflect.Message {
	mi := &file_cursor_tab_server_aiserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidiRequestId.ProtoReflect.Descriptor instead.
func (*BidiRequestId) Descriptor() ([]byte, []int) {
	return file_cursor_tab_server_aiserver_proto_rawDescGZIP(), []int{1}
}

func (x *BidiRequestId) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_cursor_tab_server_aiserver_proto protoreflect.FileDescriptor

const file_cursor_tab_server_aiserver_proto_rawDesc = "" +
	"\n" +
	" cursor-tab-server-aiserver.proto\x12\vaiserver.v1\"\x85\x01\n" +
	"\x11BidiAppendRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x129\n" +
	"\n" +
	"request_id\x18\x02 \x01(\v2\x1a.aiserver.v1.BidiRequestIdR\trequestId\x12!\n" +
	"\fappend_seqno\x18\x03 \x01(\x03R\vappendSeqno\".\n" +
	"\rBidiRequestId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestIdBJZHgithub.com/leokun/cursor-tab-server/internal/proto/aiserverv1;aiserverv1b\x06proto3"

var (
	file_cursor_tab_server_aiserver_proto_rawDescOnce sync.Once
	file_cursor_tab_server_aiserver_proto_rawDescData []byte
)

func file_cursor_tab_server_aiserver_proto_rawDescGZIP() []byte {
	file_cursor_tab_server_aiserver_proto_rawDescOnce.Do(func() {
		file_cursor_tab_server_aiserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cursor_tab_server_aiserver_proto_rawDesc), len(file_cursor_tab_server_aiserver_proto_rawDesc)))
	})
	return file_cursor_tab_server_aiserver_proto_rawDescData
}

var file_cursor_tab_server_aiserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cursor_tab_server_aiserver_proto_goTypes = []any{
	(*BidiAppendRequest)(nil), // 0: aiserver.v1.BidiAppendRequest
	(*BidiRequestId)(nil),     // 1: aiserver.v1.BidiRequestId
}
var file_cursor_tab_server_aiserver_proto_depIdxs = []int32{
	1, // 0: aiserver.v1.BidiAppendRequest.request_id:type_name -> aiserver.v1.BidiRequestId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cursor_tab_server_aiserver_proto_init() }
func file_cursor_tab_server_aiserver_proto_init() {
	if File_cursor_tab_server_aiserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cursor_tab_server_aiserver_proto_rawDesc), len(file_cursor_tab_server_aiserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cursor_tab_server_aiserver_proto_goTypes,
		DependencyIndexes: file_cursor_tab_server_aiserver_proto_depIdxs,
		MessageInfos:      file_cursor_tab_server_aiserver_proto_msgTypes,
	}.Build()
	File_cursor_tab_server_aiserver_proto = out.File
	file_cursor_tab_server_aiserver_proto_goTypes = nil
	file_cursor_tab_server_aiserver_proto_depIdxs = nil
}
